### ISSUE TITLE
Modify CI for upload package to PackageCloud.io

### ISSUE THREAD

**Issue by cmunyoz** [soltecsis/fwcloud-agent#25]
Documentation:  https://packagecloud.io/docs#github_actions

For example:
```yml
name: Push to packagecloud
  on: [push]
  jobs:
    Push-to-packagecloud:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v2
          
        - name: Upload package PackageCloud.io
          uses: danielmundi/upload-packagecloud@v1
          with:
            PACKAGE-NAME: fwcloud-pkg
            PACKAGECLOUD-USERNAME: soltecsis
            PACKAGECLOUD-REPO: FWCloud
            PACKAGECLOUD-DISTRIB: ubuntu/focal
            PACKAGECLOUD-TOKEN: ${{ secrets.af0098c64150768736d534ffeea6ccebc5008a06ae957e55 }}
```

Changing the PACKAGECLOUD-DISTRIB for each distribution/version that we have in the repository.
Now we have the next combinations for the .deb package:
debian/jessie
debian/bullseye
debian/buster
ubuntu/bionic
ubuntu/jammy
ubuntu/focal

And for the rpm package the next ones:
ol/7
ol/8
el/7
el/7
fedora/35
fedora/36
